{% set name = "sentence-transformers" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e5a411845910275fd166bacb01d28b7f79537d3550628ae42309dbdd3d5670d1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - pytorch >=1.11.0
    - transformers >=4.41.0,<5.0.0
    - huggingface_hub >=0.20.0
    - pillow

test:
  imports:
    - sentence_transformers
    - sentence_transformers.datasets
    - sentence_transformers.evaluation
    - sentence_transformers.losses
    - sentence_transformers.models
    - sentence_transformers.models.tokenizer
    - sentence_transformers.readers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/UKPLab/sentence-transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Sentence Embeddings using BERT / RoBERTa / XLNet
  description: |
    ## Sentence Transformers: Multilingual Sentence, Paragraph, and Image Embeddings using BERT & Co.

    This framework provides an easy method to compute dense vector representations for sentences, 
    paragraphs, and images. The models are based on transformer networks like 
    BERT / RoBERTa / XLM-RoBERTa etc. and achieve state-of-the-art performance in various task. 
    Text is embedding in vector space such that similar text is close and can efficiently be 
    found using cosine similarity.

    PyPI: [https://pypi.org/project/sentence-transformers/](https://pypi.org/project/sentence-transformers/)

  doc_url: https://pypi.org/project/sentence-transformers/
  dev_url: https://github.com/UKPLab/sentence-transformers

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
    - sugatoray
    - glemaitre
